### ISSUE TITLE
location_id mapping in gold

### ISSUE THREAD

**Issue by catalamarti** [oxford-pharmacoepi/cdm-etl-gold#20]
**Describe the problem**
So currently the field location_id in person table is 0 always. And if you want to get the location_id you have to get it joining person table with care_site table to get the location_id. Could this be done before hand and include the equivalent location_id in the person table? Or is there any reason why location_id is 0 in person table? @adelmestri @teenwyman 

**Affected databases**
At least all gold databases. And I think aurum data cuts too.

**Tag for awareness**
FYI: @edward-burn @ilovemane @daniellenewby @nmercadeb @albertpratsu

**Comment by teenwyman** [comment]
Hi @catalamarti 

Referring to [OMOP CDM specification](https://ohdsi.github.io/CommonDataModel/cdm54.html#PERSON), the location_id in _Person_ is the physical address of the person which is not provided by CPRD. That's why all location_ids in Person are null. 

The location_id in _Care Site_ is referring the physical location of the Care Site. This information is related to _Provider_, not _Person_.
